### ISSUE TITLE
Should now also work with MetronomeIM

### ISSUE THREAD

**Issue by poVoq** [jsxc/xmpp-cloud-auth#65]
See:
https://github.com/maranda/metronome/issues/386

Metronome is a much diverged fork of Prosody with some arguably better usability and full support for platforms like Movim. It has recently picked up development again.

**Comment by MarcelWaldvogel** [comment]
Thanks! Is **MetronomeIM** already mature enough to present it as an alternative to **Prosody** in the docs?

What are the main changes to `mod_auth_external` between _Prosody_ and _MetronomeIM_? The history only lists **maranda**'s changes.

At least some of the _Prosody_/`mod_auth_external` problems are due to `lua-lpty`. Getting rid of this would make things more stable.

In the past weeks, I have become a fan of [socket activation](http://0pointer.de/blog/projects/socket-activation.html), which is really powerful in *systemd* (better support for it is currently implemented in a private branch). Would that be an incentive to move away from process launching to socket activation? (I considered writing `mod_auth_socket`, but then went for the smaller changes in 0ca3a47b1dd).

**Comment by poVoq** [comment]
From an end-user perspective it is probably more mature than Prosody, but it lacks some of the customization options Prosody has.

Sorry, for the technical details you need to ask @maranda

**Comment by maranda** [comment]
It's just a simple backport of the module to be compatible with Metronome API, it still relies on lpty, so if there're issues with that, they'll probably still be there although using a version that does support non-blocking calls of lpty should ease the issues me thinks.

**Comment by sualko** [comment]
Thanks for the work and the update. Keep up the good work :+1:
